improved build script even further

diff --git a/autobuild b/autobuild
--- a/autobuild
+++ b/autobuild
@@ -8,32 +8,54 @@ ADDFLAGS=""
 COMPRESS=1
 
 show_help() {
-    echo "Usage: $0 [OPTION] [ARG]"
-    echo
-    echo "  -h     Show this help message and exit."
-    echo "  -d [X] Build the program in debug mode. If there's any argument given to this flag - build with GraphicDebugging"
-    echo
-    echo "  Note: If no flags are given, the program will be built in release mode."
-    echo
-    exit 0
+	echo "Usage: $0 [OPTION] [ARG]"
+	echo
+	echo "      Common flags:"
+	echo
+	echo "  -h, --help             Show this help message and exit."
+	echo "  -d, --debug [X]        Build the program in debug mode. If there's any argument given to this flag - build with GraphicDebugging"
+	echo
+	echo "      Compression settings:"
+	echo
+	echo "  -n, --nocompression    [OVERRIDE] - Don't apply any additional compression to compiled executable"
+	echo "  -f, --forcecompression [OVERRIDE] - Force compression on compiled executable"
+	echo
+	echo "  Note: If no flags are given, the program will be built in release mode with extra compression afterwards."
+	echo
+	exit 0
 }
 
 # To build        Debug - use `./autobuild -d`
 # To build GraphicDebug - use `./autobuild -d X`
-while getopts "h?d" opt; do
-  case $opt in
-    h|\?)
-        show_help
-        exit 0 ;;
+while [[ $# -gt 0 ]]; do
+	case $1 in
+		-d|--debug) 
+			if [[ -n $2 ]]; then
+				ADDFLAGS="$ADDFLAGS DEBUG=1 GRDBG=1"
+				shift
+			else
+				ADDFLAGS="$ADDFLAGS DEBUG=1"
+			fi
+			COMPRESS=0 ;;
 
-    d)  eval nextopt=\${$OPTIND}
-        ADDFLAGS="$ADDFLAGS DEBUG=1"
-        if [[ -n $nextopt && $nextopt != -* ]]; then
-            OPTIND=$((OPTIND + 1))
-            ADDFLAGS="$ADDFLAGS GRDBG=1"
-        fi 
-        COMPRESS=0 ;;
-  esac
+		-h|--help)
+			show_help
+			exit 0 ;;
+		
+		-n|--nocompression)
+			echo Will not compress compiled executable.
+			COMPRESS=0 ;;
+
+		-*|--*)
+      echo "Unknown option $1"
+			show_help
+      exit 1
+      ;;
+
+		*)
+			break ;;
+	esac
+	shift
 done
 
 # Just build with config in Makefile
@@ -41,14 +63,14 @@ make clean && make $ADDFLAGS
 
 # Compress if not building Debug.
 if [[ $COMPRESS = 1 ]]; then
-    # Stripping everything that isn't required to launch the app
-    strip -x -X -s -R .gnu.version -R .gnu.version_r. output/main
+	# Stripping everything that isn't required to launch the app
+	strip -x -X -s -R .gnu.version -R .gnu.version_r. output/main
 
-    if command -p which upx; then
-        echo "UPX found, proceeding to compress the binary..."
-        upx --best --compress-icons=3 --ultra-brute output/main
-    else
-        echo "UPX not found. Exiting..."
-        exit 0
-    fi
+	if command -p which upx; then
+		echo "UPX found, proceeding to compress the binary..."
+		upx --best --compress-icons=3 --ultra-brute output/main
+	else
+		echo "UPX not found. Exiting..."
+		exit 0
+	fi
 fi
